Check placeholder records and handle validation
10up/ads-txt pull request #129
Opened 2023-01-30 18:27 UTC by ankitrox

### Description of the Change

Closes #78 

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-02-06 04:03 UTC, peterwilsoncc reviewed
@ankitrox Thanks for the pull request.

Rather than use a static, would it be possible to check if both placeholder and valid records exist within the save function?

https://github.com/10up/ads-txt/blob/a00bdce22ec238acc0d1d599c448bb62af53d2db/inc/save.php#L34-L46

Statics can be difficult to check and while testing the changes with the `test_validate_line` function, I discovered the static was affecting other tests.

2023-04-10 21:18 UTC, jeffpaul commented
@ankitrox any chance you're able to handle the code review item above?

2023-06-19 19:15 UTC, ankitrox commented
@peterwilsoncc Thanks for the review :) 

I wanted those couple of variables to be persistent across multiple function calls, but I agree that static may not be the idea ones as far as unit tests are concerned.

I have changed it to use options table in order for them to be persistent. This will also be handy for unit tests.

2023-07-03 00:48 UTC, peterwilsoncc requested changes
I've added quite a few suggestions inline to avoid thrashing the database with option updates. 

To record the line number, I've switch from an option to a static variable. (This may need further thought)

To record the presence of a placeholder, I've added a value to the returned array in `validate_line()`.

While testing, I noticed that the order of lines affects the warnings shown. If I place a valid record above the placeholder record I am shown the warning "Your ads.txt indicates no authorized advertising sellers."

<img width="563" alt="Screen Shot 2023-07-03 at 10 43 52 am" src="https://github.com/10up/ads-txt/assets/519727/c024ab89-22be-4b13-b983-64d57f154870">

If I place the two lines in the reverse order, I also get a message that "Ads.txt contains placeholder record with another records."

<img width="618" alt="Screen Shot 2023-07-03 at 10 46 26 am" src="https://github.com/10up/ads-txt/assets/519727/eecebe70-9c59-4ca7-8fb6-c9efd52730c0">

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +
```suggestion
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
>  	$response  = array();
```suggestion
	$response  = array();
	$has_placeholder_record = false;
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
>  		if ( ! empty( $result['errors'] ) ) {
Above, change the `validate_line()` call to

```php
$result      = validate_line( $line, $line_number, $has_placeholder_record );
```

(Sorry, I can't suggest as it's outside the diff)

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +		}
```suggestion
		}

		if ( ! empty( $result['is_placeholder_record'] ) ) {
			$has_placeholder_record = true;
		}
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +
```suggestion
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
>  function validate_line( $line, $line_number ) {
```suggestion
function validate_line( $line, $line_number, $has_placeholder_record = false ) {
```

Will need a docblock changes but I can't add it as it's outside the diff.

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +	$record_lines           = get_option( ADS_TXT_RECORD_LINES_OPTION_NAME, 0 );
```suggestion
	static $record_lines           = 0;
	$is_placeholder_record = false;
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +			update_option( ADS_TXT_RECORD_LINES_OPTION_NAME, $record_lines ); // Increment record lines.
```suggestion
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +				update_option( ADS_TXT_HAS_PLACEHOLDER_OPTION_NAME, true, false );
```suggestion
```

2023-07-03 00:48 UTC, peterwilsoncc commented on inc/save.php
> +		'warnings'  => $warnings,
```suggestion
		'warnings'  => $warnings,
		'is_placeholder_record' => $is_placeholder_record,
```

2023-09-01 01:15 UTC, peterwilsoncc commented
I just tested this and am still seeing the no authorized resellers warning when the file contains both a placeholder and a valid record. 

I did some testing to see if I could come up with an approach that worked but comment lines ended up suppressing the error if the file contained placeholders and comments (which is just as bad, if not worse).

My thoughts are:

* rename `has_placeholder_records` to `has_only_placeholder_records`, in the validate_file function set it to `null`
* if we find a valid line, set the renamed variable to `false`
* if we find a placeholder and the existing value is `null`, set it to true.
* show the warning if the value is either null or true

We'll need to account for:
* comments: no affect on the value
* empty lines: no affect on the value
* invalid records: no affect on the value
* valid record
* placeholders

2024-03-01 15:06 UTC, ankitrox commented
Thank you @peterwilsoncc 

I have added the fix as per Peter's suggestion and it seems to be working fine. Also, added the unit test for the placeholder record.

CC: @jeffpaul

2024-03-05 04:56 UTC, peterwilsoncc approved these changes
This looks good to me and tests well. Thank you so much for your patience as we got this working.

I pushed a couple of minor changes:
* 811fabca5eb4910cb4e24288701e4e0711af6235 to make sure the optional tag value was set
* f1a56e501b201458e92e5565a633f5c56719b104 to remove some sniff suppression that were not needed.

2024-03-05 04:56 UTC, merged